version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app/api
      - ./logs/:/logs/
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M